spring:
  application.name: gateway
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

  sql:
    init:
      mode: always
      platform: h2

  h2:
    console:
      enabled: true

server:
  port: 8080

bff:
  security: database
  clients:
    people-url: http://localhost:8081
    reservation-url: http://localhost:8082
    rooms-url: http://localhost:8083